### ISSUE TITLE
Grain filtering and WSS/HTTPS and ASP.NET integration?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [OrleansContrib/OrleansHttp#5]
We want to expose some (only part of grains) as secured (wsS/httpS) API. Is it possible? How much effort you see to be done to make such feature?

**Comment by richorama** [comment]
Hi @dzmitry-lahoda, you should probably not use this project, and either: 

1. Stand up your own API using ASP.NET
1. Check the state of some work @ReubenBond was doing to create an HTTP API for Orleans.
